import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "./components/footer";
import Navbar from "./components/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kanki Studios",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="overflow-x-hidden flex flex-col relative max-h-screen xl:overflow-y-scroll">
      <Navbar />
      <div className={inter.className}>{children}</div>
      <Footer />
    </div>
  );
}
